import Modal from '../../../components/common/Modal'
import type { Caja, Ingrediente, Producto, Proveedor } from '../types'

interface Props {
  producto: Producto | Omit<Producto, 'id_producto'>; ingrediente: Ingrediente; proveedor: Proveedor; caja: Caja
  productoOpen: boolean; ingredienteOpen: boolean; proveedorOpen: boolean; cajaOpen: boolean
  editProducto: boolean; editIngrediente: boolean; editProveedor: boolean; editCaja: boolean
  savingProducto: boolean; savingIngrediente: boolean; savingProveedor: boolean; savingCaja: boolean
  errorProducto: string | null; errorIngrediente: string | null; errorProveedor: string | null; errorCaja: string | null
  setProducto: (value: Producto | Omit<Producto, 'id_producto'>) => void; setIngrediente: (value: Ingrediente) => void; setProveedor: (value: Proveedor) => void; setCaja: (value: Caja) => void
  closeProducto: () => void; closeIngrediente: () => void; closeProveedor: () => void; closeCaja: () => void
  submitProducto: () => void; submitIngrediente: () => void; submitProveedor: () => void; submitCaja: () => void
}

const field = "w-full rounded-[10px] border-[1.5px] border-[var(--borde)] bg-[var(--bg)] px-3.5 py-2.5 font-['DM_Sans'] text-[0.95rem] text-[var(--texto)] outline-none"
function GerenteModals({ producto, ingrediente, proveedor, caja, productoOpen, ingredienteOpen, proveedorOpen, cajaOpen, editProducto, editIngrediente, editProveedor, editCaja, savingProducto, savingIngrediente, savingProveedor, savingCaja, errorProducto, errorIngrediente, errorProveedor, errorCaja, setProducto, setIngrediente, setProveedor, setCaja, closeProducto, closeIngrediente, closeProveedor, closeCaja, submitProducto, submitIngrediente, submitProveedor, submitCaja }: Props) {
  const actions = (close: () => void, submit: () => void, saving: boolean, edit: boolean) => <div className="mt-5 flex justify-end gap-3"><button className="rounded-[10px] border border-[var(--borde)] bg-[#f9f5f0] px-4 py-2.5 text-[0.875rem] font-semibold text-[var(--texto-muted)]" onClick={close} disabled={saving}>Cancelar</button><button className="rounded-[10px] bg-[var(--rojo)] px-4 py-2.5 text-[0.875rem] font-semibold text-white" onClick={submit} disabled={saving}>{saving ? 'Guardando...' : edit ? 'Actualizar' : 'Crear'}</button></div>
  return <>
    <Modal isOpen={productoOpen} onClose={closeProducto}><div className="min-w-[400px] p-6"><h3 className="mb-4 font-['Syne'] text-[1.2rem] font-bold text-[var(--texto)]">{editProducto ? 'Editar Producto' : 'Nuevo Producto'}</h3>{errorProducto && <p className="mb-3 text-[0.85rem] text-[var(--rojo)]">{errorProducto}</p>}<div className="flex flex-col gap-3"><input placeholder="Nombre *" value={producto.Nombre} onChange={e => setProducto({ ...producto, Nombre: e.target.value })} className={field} /><textarea placeholder="Descripción" value={producto.Descripcion} onChange={e => setProducto({ ...producto, Descripcion: e.target.value })} rows={3} className={field} /><input type="number" placeholder="Precio *" value={producto.precio_venta} onChange={e => setProducto({ ...producto, precio_venta: e.target.value })} className={field} /><input placeholder="Categoría" value={producto.Categoria} onChange={e => setProducto({ ...producto, Categoria: e.target.value })} className={field} /><input placeholder="Tiempo prep. (HH:MM:SS)" value={producto.Tiempo_preparacion} onChange={e => setProducto({ ...producto, Tiempo_preparacion: e.target.value })} className={field} /><select value={producto.Estado} onChange={e => setProducto({ ...producto, Estado: Number(e.target.value) })} className={field}><option value={1}>Activo</option><option value={0}>Inactivo</option></select></div>{actions(closeProducto, submitProducto, savingProducto, editProducto)}</div></Modal>
    <Modal isOpen={ingredienteOpen} onClose={closeIngrediente}><div className="min-w-[400px] p-6"><h3 className="mb-4 font-['Syne'] text-[1.2rem] font-bold text-[var(--texto)]">{editIngrediente ? 'Editar Ingrediente' : 'Nuevo Ingrediente'}</h3>{errorIngrediente && <p className="mb-3 text-[0.85rem] text-[var(--rojo)]">{errorIngrediente}</p>}<div className="flex flex-col gap-3"><input placeholder="Nombre *" value={ingrediente.nombre} onChange={e => setIngrediente({ ...ingrediente, nombre: e.target.value })} className={field} /><textarea placeholder="Descripción" value={ingrediente.descripcion} onChange={e => setIngrediente({ ...ingrediente, descripcion: e.target.value })} rows={2} className={field} /><input placeholder="Unidad de medida" value={ingrediente.unidad_medida} onChange={e => setIngrediente({ ...ingrediente, unidad_medida: e.target.value })} className={field} /><input type="number" placeholder="Costo unitario ref." value={ingrediente.costo_unitario_ref} onChange={e => setIngrediente({ ...ingrediente, costo_unitario_ref: e.target.value })} className={field} /><input type="number" placeholder="Stock mínimo" value={ingrediente.stock_minimo} onChange={e => setIngrediente({ ...ingrediente, stock_minimo: e.target.value })} className={field} /></div>{actions(closeIngrediente, submitIngrediente, savingIngrediente, editIngrediente)}</div></Modal>
    <Modal isOpen={proveedorOpen} onClose={closeProveedor}><div className="min-w-[420px] p-6"><h3 className="mb-4 font-['Syne'] text-[1.2rem] font-bold text-[var(--texto)]">{editProveedor ? 'Editar Proveedor' : 'Nuevo Proveedor'}</h3>{errorProveedor && <p className="mb-3 text-[0.85rem] text-[var(--rojo)]">{errorProveedor}</p>}<div className="flex flex-col gap-3">{(['nombre', 'nombre_contacto', 'telefono', 'email', 'direccion', 'nit', 'tipo_proveedor'] as const).map(key => <input key={key} type={key === 'email' ? 'email' : 'text'} placeholder={key} value={proveedor[key]} onChange={e => setProveedor({ ...proveedor, [key]: e.target.value })} className={field} />)}<select value={proveedor.estado} onChange={e => setProveedor({ ...proveedor, estado: e.target.value })} className={field}><option value="ACTIVO">Activo</option><option value="INACTIVO">Inactivo</option></select></div>{actions(closeProveedor, submitProveedor, savingProveedor, editProveedor)}</div></Modal>
    <Modal isOpen={cajaOpen} onClose={closeCaja}><div className="min-w-[380px] p-6"><h3 className="mb-4 font-['Syne'] text-[1.2rem] font-bold text-[var(--texto)]">{editCaja ? 'Editar Caja' : 'Nueva Caja'}</h3>{errorCaja && <p className="mb-3 text-[0.85rem] text-[var(--rojo)]">{errorCaja}</p>}<div className="flex flex-col gap-3"><input placeholder="Nombre de la caja *" value={caja.nombre} onChange={e => setCaja({ ...caja, nombre: e.target.value })} className={field} /><select value={caja.estado} onChange={e => setCaja({ ...caja, estado: e.target.value })} className={field}><option value="ACTIVA">Activa</option><option value="INACTIVA">Inactiva</option></select></div>{actions(closeCaja, submitCaja, savingCaja, editCaja)}</div></Modal>
  </>
}
export default GerenteModals